DROP TABLE IF EXISTS urls;

CREATE TABLE Urls (
    id INTEGER PRIMARY KEY AUTOINCREMENT, 
    actual_url VARCHAR (255) NOT NULL, 
    alias_url VARCHAR (50) NOT NULL,
    creation_date DATETIME DEFAULT CURRENT_TIMESTAMP
); 